version: 2.1
orbs:
  maven: circleci/maven@1.3.0

workflows:
    example-workflow:
      jobs:
        - maven/test:
            app_src_directory: /MatchAnalysis
            test_results_path: target/surefire-reports(string) 
